version: "3.2"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - ./app-config.yaml:/usr/app/app-config.yaml
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: codex-notes
      POSTGRES_PASSWORD: example
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data