services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 127.0.0.1:1337:1337
    volumes:
      - ./app-config.yaml:/usr/app/app-config.yaml
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: codex
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  s3:
    image: minio/minio
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    volumes:
      - ./s3:/data
    environment:
      MINIO_ROOT_USER: codex
      MINIO_ROOT_PASSWORD: minio12345
      MINIO_REGION: my-region
    command: server --console-address ":9001" /data
