source : https://github.com/codex-team/notes.api/blob/main/src/presentation/http/router/auth.ts#L42

path: /auth
  method: post
    tag: 
     -fastify
    summary: check, access, remove, refresh token
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/session'
      
    responses:
        401:
          type: "application/json"
          reply: ErrorResponse
          body:
            # creatorId: "@presentation/http/types/HttpResponse.js"
            # StatusCodes: UNAUTHORIZED
            message: 'Session is not valid'
                
        
        200:
          type: "application/json"
          reply: AuthSession
          body:
            accessToken: ''
            refreshToken: ''
            # creatorId: '@domain/service/auth.js'
            # signAccessToken :  userSession.userId
            # removeSessionByRefreshToken: token
            # signRefreshToken : userSession.userId

          

components:
  schemas:
    session:
      token:
        type: string
        example: 123

