/**
 * Notes settings entity
 */
export default interface NoteSettingsPublic {
  /**
   * Just unique property identifier
   */
  id: number;
  /**
   * Custom hostname
   */
  customHostname?: string;

  /**
   * Is note public for everyone or only for collaborators
   */
  isPublic: boolean;
}

/**
 * Notes settings creation attributes, omitting id, because it's generated by database
 */
type NoteSettingsCreationAttributes = Omit<NoteSettingsPublic, 'id'>;

export type {
  NoteSettingsCreationAttributes
};
