/**
 * Notes settings entity
 */
export default interface NotesSettings {
  /**
   * Just unique property identifier
   */
  id: number;

  /**
   * Related note id
   */
  noteId: number;

  /**
   * Custom hostname
   */
  customHostname?: string;

  /**
   * Is note public for everyone or only for collaborators
   */
  enabled: boolean;
}

/**
 * Notes settings creation attributes, omitting id, because it's generated by database
 */
type NotesSettingsCreationAttributes = Omit<NotesSettings, 'id'>;

export type {
  NotesSettingsCreationAttributes
};
