import type { Team } from './team.js';

/**
 * Invitation hash. It's used to invite users to team
 */
export type InvitationHash = string;

/**
 * Position of the note in the sidebar
 */
export type SidebarPosition = 'edge' | 'content' | 'none';

/**
 * Notes settings entity
 */
export default interface NoteSettings {
  /**
   * Just unique property identifier
   */
  id: number;

  /**
   * Related note id
   */
  noteId: number;

  /**
   * Custom hostname
   */
  customHostname?: string ;

  /**
   * Is note public for everyone or only for collaborators
   */
  isPublic: boolean;

  /**
   * Invitation hash
   */
  invitationHash: InvitationHash;

  /**
   * Note cover image id
   */
  cover: string;

  /**
   * Position of the note in the sidebar
   */
  sidebarPosition: SidebarPosition;

  /**
   * Team members. Team is empty by default because note creator is not stored in team
   */
  team?: Team;
}

/**
 * Attributes of public note settings
 */
type NoteSettingsPublicProperties = 'customHostname' | 'isPublic' | 'invitationHash' | 'team' | 'cover' | 'sidebarPosition' ;

export interface NoteSettingsPublic extends Pick<NoteSettings, NoteSettingsPublicProperties> {}

/**
 * Define note settings for public usage
 * @param noteSettings - note settings data
 */
export function definePublicNoteSettings(noteSettings: NoteSettings): NoteSettingsPublic {
  return {
    customHostname: noteSettings.customHostname,
    isPublic: noteSettings.isPublic,
    invitationHash: noteSettings.invitationHash,
    team: noteSettings.team,
    cover: noteSettings.cover,
    sidebarPosition: noteSettings.sidebarPosition,
  };
}

/**
 * Notes settings creation attributes, omitting id, because it's generated by database, omitting cover, because it should be generated after insertion of the note
 */
type NoteSettingsCreationAttributes = Omit<NoteSettings, 'id' | 'cover' | 'sidebarPosition'>;

export type {
  NoteSettingsCreationAttributes
};
