/**
 * Note entity
 */
export default interface Note {
  /**
   * Note id
   */
  id: number;

  /**
   * Note title
   */
  title: string;

  /**
   * Note content
   */
  content: JSON;

  /**
   * Note creator
   */
  creatorId: number;
}


/**
 * Notes creation attributes, omitting id, because it's generated by database
 */
type NoteCreationAttributes = Omit<Note, 'id'>;

export type {
  NoteCreationAttributes
};
