name: Build and start

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-start:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: codex
          POSTGRES_DB: notes
        ports:
            - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Build and start the app
    runs-on: ubuntu-22.04
    steps:
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres createuser -s -d -r -w runner

          - name: Install postgresql-client (psql)
          run: |
            apt update -y
            apt install -y postgresql-client
            psql --version
  
      - name: Check DB connection
        run: |
          psql "postgres://codex:postgres@localhost:5432/notes" <<EOF
            CREATE TABLE test (id INT);
            INSERT INTO test (id) VALUES (123);
            INSERT INTO test (id) VALUES (456);
            INSERT INTO test (id) VALUES (789);
            SELECT * FROM test;
          EOF

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Change database address
        run: |
          sed -i "s/@postgres/@localhost/" app-config.yaml

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Start
        run: node dist/index.js -c app-config.yaml
