name: Build and start

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-start:
    name: Build and start the app
    runs-on: ubuntu-22.04
    steps:
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres createuser -s -d -r -w runner

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Change database address
        run: |
          sed -i "s/@postgres/@localhost/" app-config.yaml

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Start
        run: node dist/index.js -c app-config.yaml
