name: Run ESlint check

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  pull_request:

jobs:
  eslint:
    name: Run eslint check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Install dependencies
        run: |
          yarn install
    
      - name: Run ESLint
        run: yarn lint