name: Build and start

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-start:
    name: Build and start the app
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: codex
          POSTGRES_DB: notes
          POSTGRES_PASSWORD: postgres
        ports:
          - 127.0.0.1:5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./database:/var/lib/postgresql/data

    steps:
      - name: Wait for PostgreSQL
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      - name: Make runner the owner of database folder
        run: |
          sudo chmod -R 777 ./database

      - name: Restart postgres service
        run: |
          sudo service postgresql restart

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true

      - name: Start
        run: node dist/index.js -c app-config.yaml
